---
name: "ci"

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build
        run: ./tools/ci/build.sh

      - name: test
        run: ./tools/ci/test.sh
